# Generated by Django 3.0.3 on 2020-06-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(default='', max_length=100)),
                ('student_name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', help_text='A valid email address, please.', max_length=254)),
                ('phone', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='recognition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_title', models.CharField(max_length=140)),
                ('rec_subtitle', models.CharField(max_length=255)),
                ('rec_content', models.TextField(default='<text here>')),
                ('rec_type', models.CharField(max_length=140)),
                ('rec_img', models.ImageField(default='', upload_to='static/main/img/')),
            ],
        ),
    ]
