# Generated by Django 3.0.3 on 2020-06-09 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='section',
        ),
    ]
