# Generated by Django 3.0.3 on 2020-06-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200616_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='age',
            field=models.SmallIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='reasons',
            field=models.TextField(default='Unknown'),
        ),
    ]
