# Generated by Django 3.0.3 on 2020-06-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200620_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognition',
            name='rec_img',
            field=models.ImageField(default='', upload_to='static/main/img/'),
        ),
    ]
